### ISSUE TITLE
Uploading and serving large repos/modules on deno.land/x

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno_website2#1743]
I'm wondering whether there is a file size limit for modules uploaded to deno.land/x? My guess that tens of megabytes is okay, and a few hundred megabytes (e.g. a module containing [400mb of machine learning models split into 4mb files](https://github.com/josephrocca/dalle-encoder-decoder-js)) is too much, and not what deno.land/x is designed for.

As a point of reference, it seems that it's possible to upload a package that's at least a hundred megabyte to NPM, but it doesn't seem common, and I'm not sure what the rules are in case users go significantly over that.

I'd obviously be happy if it were fine to upload large modules to deno.land/x, but my concern is that it may not be financially sustainable if people end up using it as free storage/bandwidth for their bulky client-side files.

**Comment by wperron** [comment]
Yes, there is a limit of [20Mb](https://github.com/denoland/deno_registry2/blob/main/api/async/publish.ts#L30) for total module size -- if you need more than that you can open a request on https://github.com/denoland/deno_registry2 or contact me or @lucacasonato by email/Discord DM. 400Mb is a lot though, and you might see intermittent issues since we're running on Lambda which has a total filesystem size limit of 512Mb (including your module's source code _and_ the registry's build code and dependencies).

**Comment by josephrocca** [comment]
Good to know, thanks!
