### ISSUE TITLE
Add link to Deploy in Nav bar, displayed with 1% probability

### ISSUE THREAD

**Issue by ry** [denoland/deno_website2#1820]
We want to start advertising https://deno.com/deploy on the home page - but Deploy isn't ready for the prime time - so we want the ability to tune how often it is displayed.

I think to start with we can display it for every 1/100 page loads.

We might have to move some things around to make room for this... It doesn't seem like there's much space left.

**Comment by AaronO** [comment]
We could maybe consider simplifying the wording and re-arranging the "Install" link, something like this:

![image](https://user-images.githubusercontent.com/949223/129027525-010cd793-42fe-4c9f-b5bc-f25821eb339b.png)

**Comment by meszarosdezso** [comment]
How about grouping the two links to the module pages into a dropdown menu? ( Because it's shown on hover, it's not necessarily that much worse ux, but can save some space, and enhances the connection between the two menu items )

https://user-images.githubusercontent.com/45368713/129717240-4e288bdc-72b2-4661-916d-bc1d35052a38.mov

Also, renaming **Runtime API** to **Docs** can save a lot of space, and while they are not necessarily meaning the same, _I think_ Docs is more a "beginner friendly" (and common) term even for API documentations like this ( feel free to disagree with me on this (: ).

I also agree with Aaron on putting the **Install** link on the landing page, since it does not navigate to another page. I imagined sth like this:

<img width="747" alt="Screenshot 2021-08-17 at 13 43 37" src="https://user-images.githubusercontent.com/45368713/129719900-2d7b36cd-5769-47a5-a5c4-031cd3a72249.png">


otoh, since you want to advertise Deploy ( not just randomly show it in the menu, because seeing an item in the main navigation menu can make the user expect it to be there the next time they visit the site ), how about showing a full-width banner (around 80px tall) on the top of the page, with the background of the animation on https://deno.com/deploy and saying sth like _"Deploy your Deno app in seconds!"_ ? ( I can't showcase what I have in mind rn, as that animation is drawn on a canvas )

**+1** Can we store in the user's browser if they have clicked on the Deploy ad, so that the ad is visible to them permanently?

thoughts?(:

**Comment by satyarohith** [comment]
@manyuanrong Thanks for your input.

> How about grouping the two links to the module pages into a dropdown menu?

I feel like dropdowns are a bit complex, and considering we can fit the menu items, it might not be necessary. 

> renaming Runtime API to Docs can save a lot of space, and while they are not necessarily meaning the same, I think Docs is more a "beginner friendly"

I agree with your concern, but beginners are more likely to start with the manual than the runtime API.

**Comment by meszarosdezso** [comment]
@satyarohith I agree with both, it looks like in your PR everything fits there just fine, and I like how the Install link gets the attention! One more nit-pick about the UI if you don't mind: can we try showing the version number with a `monospaced` font? ( I also changed the margin to `mt-8` for a bit more whitespace between the title and the button )

<img width="630" alt="Screenshot 2021-08-18 at 9 28 36" src="https://user-images.githubusercontent.com/45368713/129856348-77984a39-9172-4442-b772-d607dcc3fedb.png">

Sorry, i'm just throwing ideas at you, I know it is not the main concern here how things are spaced tho (:
