### ISSUE TITLE
bring back "normalize" feature in the benchmark plots 

### ISSUE THREAD

**Issue by ry** [denoland/deno_website2#26]
as was done in https://github.com/denoland/deno/pull/2919

cc @lucacasonato

**Comment by lucacasonato** [comment]
I'll take this on - should be a lot cleaner in React.

**Comment by lucacasonato** [comment]
So there are some issues with c3-react. The C3Chart component does not react to state updates (like the label) - this means that when I change for example the label, the chart does not change. I can also not use multiple charts and just hide/unhide them like I did on the original site because then c3 does not properly size the chart and content overflows on the bottom. Do you have any ideas on how we could deal with this? We should consider using a different chart library that is more reactive if we can't figure this with c3.

**Comment by ry** [comment]
@lucacasonato That sucks. I don't have any ideas. I'm happy to explore a different charting module.

**Comment by lucacasonato** [comment]
I'll look into some other chart modules then. I saw some interesting ones while researching this issue yesterday.

**Comment by lucacasonato** [comment]
Fixed by #39
