### ISSUE TITLE
Version needs to be removed from import of example program on home page

### ISSUE THREAD

**Issue by rsromanowski** [denoland/deno_website2#675]
Under getting started at https://deno.land/#getting-started, there is a complex starter program that causes an assertion error when run locally. I was able to resolve this by removing the version in the import:

Change https://deno.land/std@0.50.0/http/server.ts to https://deno.land/std/http/server.ts

**Comment by nayeemrmn** [comment]
@rsromanowski The problem is that https://deno.land/std@0.50.0 is a version behind latest, while https://deno.land/std is the master branch.

This time the latter happened to work, but in general neither are guaranteed to work. Ideally the latest version would always be used on the getting started examples. I think we should leave a comment in `std/version.ts` listing the locations of code examples which need to be kept in sync.
