### ISSUE TITLE
Sidebar menu does not close

### ISSUE THREAD

**Issue by AM-77** [denoland/deno_website2#725]
The sidebar menu does not close ( the close button and the title link are not responding  ) on the [introduction page](https://deno.land/manual/introduction),  [standard library page](https://deno.land/manual/standard_library), and [testing page](https://deno.land/manual/testing)

Edit: more details
this happens only when you are in one of those pages and open the sidebar menu, then trying to close it and staying in the same page (it works normal if you change the page).

**Comment by zrthxn** [comment]
I've tried a few things and it doesn't seem that there's anything wrong with the logic itself, it's pretty straightforward. I'm guessing that when you navigate to a different page the sidebar closes because the state of the Manual component is reset to `showSidebar = false`.

Adding a simple dismount works but isn't a solution
```tsx
{ 
  showSidebar ? (
     <Transition show={showSidebar}>
       ...
     </Transition>
  ) : null 
}
```

Might be something to do with the `CSSTransition` component since its callbacks (onExiting and onExit) don't get called.
