### ISSUE TITLE
Need of Guidelines for Third Party Modules (People Creating aliases to original)

### ISSUE THREAD

**Issue by Swap76** [denoland/deno_website2#861]
@ry has always said that we can benefit from the different communities at every step but does use of great NodeJS module in the back of Deno Third-Party Module complete ripe off without intimating the particular NodeJS module community makes sense?

Example: Guys at mime-db are fine with it but just a concered of about such thing
<img width="1008" alt="Screenshot 2020-05-28 at 4 02 26 AM" src="https://user-images.githubusercontent.com/37082605/83079733-18d15080-a09a-11ea-8beb-b6ce7dd80e9a.png">

We are striving for a decentralized package delivery but I think we need to have some guidelines/rules for the package to become eligible to be added on the website.

@lucacasonato

**Comment by alirealasad** [comment]
Hi, that module is created by me, I didn't mean to rip off anybody. I created it because I wanted to use it for my other projects. should I remove it or something.

**Comment by Swap76** [comment]
@alirealasad No no I didn't mean that 

I used it as example sorry for that, My point was as we are thriving for the decentralized distribution so I think we need some minimal rule but I studied the licenses so I found out that it's completely perfect to use like this :-)

**Comment by michaeldesu** [comment]
>  I think we need to have some guidelines/rules for the package to become eligible to be added on the website.

I wasn't sure whether to raise a new post or append to this [issue](https://github.com/denoland/deno_website2/issues/406) but the above statement resonated with me regarding my suggestion. Forgive me also, I'm a new deno user & relatively new to JS.

As a new user, I've found it frustrating to use some third-party modules because the documentation is so variable in quality, particularly around usage. I understand providing a module to deno.land is akin to a github repo link, but I'd like to suggest a posting requirement that any third-party module submitted to appear on deno-land must have a (tested) usage or example. 

Here's a good [case](https://deno.land/x/quote_lib@v1.2) of a module that's got a working usage/example. But [another](https://deno.land/x/input@2.0.2) has an example but no import line, so as a novice I'm left guessing or experimenting about how to write the import line (i.e. import InputLoop with or without the enclosing brackets, and entering the right url).

What's more frustrating is the really popular and useful third-party modules (like lodash, dayjs and sheetjs) don't appear to have any deno-related reference or examples, so I'm scratching around. I've even asked the maker of one of these, and s/he admits to not having any deno experience, so can't help.

So rather than allowing makers to just upload their modules to deno land, it would be good if they can at least test that it works with deno and provide a usage/example for eligibility to avoid new-user frustration and encourage adoption.
